Repository redhat-plumbers/systemd-rhel10, pull requests merged in 2024-07, with the labels that each got.

#19 (RHEL-46277) taint: remove unmerged-bin
  catalog/systemd.catalog.in
  catalog/systemd.pl.catalog.in
  man/org.freedesktop.systemd1.xml
  src/core/taint.c
Labels: pr/needs-ci, tracker/unapproved

#18 (RHEL-46576) presets: remove resolved
  presets/90-systemd.preset
Labels: pr/needs-ci

#23 (RHEL-46778) coredump: by default process and store core files up to 1GiB
  src/coredump/coredump.conf
Labels: ci-waived
